apiVersion: v1
kind: Pod
metadata:
  name: pod-local-pvc
spec:
  restartPolicy: Never
  containers:
    - name: ubuntu-container
      image: ubuntu
      command: ['/bin/bash', '-ec', 'cat /data/application/data.txt']
      volumeMounts:
        - mountPath:  /data/application
          name: local-volume
  volumes:
    - name: local-volume
      persistentVolumeClaim:
        claimName: pvc-local
