apiVersion: v1
kind: Pod
metadata:
  name: pod-with-emptydir-volume
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
      - mountPath: /mounted-data
        name: data-volume
  volumes:
    - name: data-volume
      emptyDir: {}
