apiVersion: v1
kind: Pod
metadata:
  name: resource-requirements-pod

spec:
  containers:
  - name: container-with-resource-requirements
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "1"
      requests:
        memory: "64Mi"
        cpu: "0.5"
