apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-depoloyment
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: first-depoloyment
          image: nginx
    